const COMPANY_POOL = [
    { company: "Apex Innovations", industry: "Healthcare", emailSuffix: "@apex.com" },
    { company: "Zenith Financial Group", industry: "Finance", emailSuffix: "@zenithfinancial.com" },
    { company: "Nexus Tech Solutions", industry: "Technology", emailSuffix: "@nexustech.com" },
    { company: "Prime Energy Corp", industry: "Energy", emailSuffix: "@primeenergy.com" },
    { company: "Stellar Marketing Agency", industry: "Marketing", emailSuffix: "@stellarmarketing.com" },
    { company: "Summit Logistics", industry: "Transportation", emailSuffix: "@summitlogistics.com" },
    { company: "Luxe Lifestyle Brands", industry: "Retail", emailSuffix: "@luxelifestyle.com" },
    { company: "Ascend Aerospace", industry: "Aerospace", emailSuffix: "@ascendaerospace.com" },
    { company: "Pinnacle Education Systems", industry: "Education", emailSuffix: "@pinnacleedu.com" },
    { company: "Nova Healthcare Systems", industry: "Healthcare", emailSuffix: "@novahealth.com" },
    { company: "Bright Future Investments", industry: "Finance", emailSuffix: "@brightfuture.com" },
    { company: "Nimbus Cloud Solutions", industry: "Technology", emailSuffix: "@nimbuscloud.com" },
    { company: "EcoWorld Renewable Energy", industry: "Energy", emailSuffix: "@ecoworldenergy.com" },
    { company: "Panorama Advertising Co.", industry: "Marketing", emailSuffix: "@panoramaadvertising.com" },
    { company: "Blue Horizon Shipping", industry: "Transportation", emailSuffix: "@bluehorizon.com" },
    { company: "Infinity Retail Group", industry: "Retail", emailSuffix: "@infinityretail.com" },
    { company: "Voyager Space Research", industry: "Aerospace", emailSuffix: "@voyagerspace.com" },
    { company: "Beacon Educational Services", industry: "Education", emailSuffix: "@beaconedu.com" },
    { company: "Helios Pharmaceuticals", industry: "Healthcare", emailSuffix: "@heliospharma.com" },
    { company: "Equinox Finance Partners", industry: "Finance", emailSuffix: "@equinoxfinance.com" },
    { company: "Aurora Tech Hub", industry: "Technology", emailSuffix: "@auroratech.com" },
    { company: "Solaris Energy Solutions", industry: "Energy", emailSuffix: "@solarisenergy.com" },
    { company: "Silverline Advertising", industry: "Marketing", emailSuffix: "@silverlinead.com" },
    { company: "Skyline Logistics", industry: "Transportation", emailSuffix: "@skylinelogistics.com" },
    { company: "Trailblazer Outdoor Gear", industry: "Retail", emailSuffix: "@trailblazergear.com" },
    { company: "Orbit Satellite Systems", industry: "Aerospace", emailSuffix: "@orbitsatellite.com" },
    { company: "Aspire Education Partners", industry: "Education", emailSuffix: "@aspireedu.com" },
    { company: "Haven Healthcare Group", industry: "Healthcare", emailSuffix: "@havenhealthcare.com" },
    { company: "Summit Asset Management", industry: "Finance", emailSuffix: "@summitasset.com" },
    { company: "Innovative Data Systems", industry: "Technology", emailSuffix: "@innovativedata.com" }
  ];

module.exports = COMPANY_POOL