const ROLES = ['AI Engineer', 'Data Scientist', 'Mobile Developer',
    'Project Manager', 'Frontend Developer', 'Backend Developer', 'UX Designer', 'UI Designer',
    'QA Tester', 'Product Owner', 'Embedded Developer', 'Electronics Engineer',
    'VR Developer', '3D Modeler', 'Desktop Developer', 'Database Administrator', 'Data Analyst', 'Event Coordinator',
    'Cryptography Specialist', 'Hardware Engineer', 'Cloud Engineer', 'Security Specialist', 'IoT Developer', 'Network Engineer', 'AR Developer',
    'Product Manager', 'Social Media Strategist', 'Marketing Specialist', 'Energy Consultant', 'Energy Specialist',
    'Solar Energy Expert', 'Safety Specialist', 'Logistics Specialist', 'Game Developer', 'Retail Expert', 'Satellite Data Analyst',
    'Aerospace Engineer', 'Drone Specialist', 'Aerospace Technician', 'Astronaut Trainer', 'Education Consultant', 'Education Specialist',
    'Science Educator'
];

const ROLE_SKILLS = {
    "AI Engineer": ["Python", "TensorFlow", "PyTorch", "Machine Learning", "Deep Learning", "Natural Language Processing", "Computer Vision", "Cloud Computing", "Big Data"],
    "Data Scientist": ["Python", "R", "SQL", "Data Visualization", "Machine Learning", "Big Data", "Statistical Analysis", "Pandas", "Matplotlib", "Jupyter"],
    "Mobile Developer": ["React Native", "Flutter", "Kotlin", "Swift", "Android SDK", "iOS Development", "Java", "Objective-C", "UI/UX for Mobile"],
    "Project Manager": ["Agile Methodologies", "Scrum", "Project Scheduling", "Risk Management", "JIRA", "Microsoft Project", "Team Leadership", "Stakeholder Management"],
    "Frontend Developer": ["ReactJS", "Angular", "VueJS", "JavaScript", "HTML5", "CSS3", "SASS", "Bootstrap", "Webpack"],
    "Backend Developer": ["Node.js", "Django", "Ruby on Rails", "Express.js", "Spring Boot", "PHP", "Go", "MySQL", "PostgreSQL"],
    "UX Designer": ["Wireframing", "User Research", "Adobe XD", "Figma", "InVision", "User Journey Mapping", "Accessibility Standards"],
    "UI Designer": ["Adobe XD", "Figma", "Sketch", "InVision", "Color Theory", "Typography", "Prototyping"],
    "QA Tester": ["Selenium", "Appium", "Postman", "JMeter", "Test Automation", "Manual Testing", "Bug Reporting", "Test Case Design"],
    "Product Owner": ["Requirement Analysis", "Backlog Management", "Agile Methodologies", "JIRA", "Stakeholder Communication", "User Stories"],
    "Embedded Developer": ["C", "C++", "Microcontroller Programming", "RTOS", "Assembly Language", "Arduino", "Raspberry Pi"],
    "Electronics Engineer": ["Circuit Design", "PCB Design", "MATLAB", "SPICE Simulation", "Analog/Digital Systems", "Microcontrollers"],
    "VR Developer": ["Unity3D", "Unreal Engine", "C#", "VR Hardware Integration", "3D Modeling Basics", "Physics Simulations"],
    "3D Modeler": ["Blender", "Maya", "ZBrush", "3ds Max", "Cinema 4D", "UV Mapping", "Texture Painting"],
    "Desktop Developer": ["C#", "Electron.js", "Qt Framework", ".NET", "JavaFX", "Python PyQt", "Tkinter"],
    "Database Administrator": ["SQL", "NoSQL", "MySQL", "PostgreSQL", "MongoDB", "Database Security", "Backup and Recovery", "Performance Tuning"],
    "Data Analyst": ["Python", "R", "Excel", "Power BI", "Tableau", "Data Cleaning", "SQL", "Statistical Analysis"],
    "Event Coordinator": ["Event Planning", "Scheduling", "Communication Skills", "Budgeting", "Vendor Management", "Logistics"],
    "Cryptography Specialist": ["Encryption Algorithms", "Blockchain", "Public Key Infrastructure (PKI)", "Cybersecurity", "Mathematical Modeling"],
    "Hardware Engineer": ["Circuit Design", "Hardware Testing", "FPGA", "ASIC Design", "Verilog/VHDL", "Embedded Systems"],
    "Cloud Engineer": ["AWS", "Azure", "Google Cloud", "Kubernetes", "Docker", "DevOps", "CI/CD", "Serverless Architecture"],
    "Security Specialist": ["Cybersecurity", "Penetration Testing", "Firewall Management", "Incident Response", "SIEM Tools", "Vulnerability Assessment"],
    "IoT Developer": ["Arduino", "Raspberry Pi", "MQTT", "Node-RED", "IoT Protocols", "Sensor Integration", "Embedded Systems"],
    "Network Engineer": ["Cisco Networking", "Routing & Switching", "Firewall Configuration", "LAN/WAN Design", "VPN", "Wireless Networking"],
    "AR Developer": ["Unity3D", "Unreal Engine", "ARKit", "ARCore", "C#", "3D Object Recognition", "Markerless Tracking"],
    "Product Manager": ["Market Research", "Product Strategy", "Agile/Scrum", "Stakeholder Communication", "Roadmap Planning"],
    "Social Media Strategist": ["Social Media Platforms", "Content Creation", "Analytics Tools", "SEO", "Engagement Strategies"],
    "Marketing Specialist": ["SEO", "Google Analytics", "Content Marketing", "Email Campaigns", "Social Media Management", "Market Research"],
    "Energy Consultant": ["Energy Auditing", "Renewable Energy Solutions", "Carbon Footprint Analysis", "Project Feasibility"],
    "Energy Specialist": ["Energy Efficiency", "Electrical Systems", "Solar Energy Systems", "Smart Grid Technologies"],
    "Solar Energy Expert": ["Solar PV Design", "Inverter Configuration", "Energy Storage Systems", "Solar ROI Analysis"],
    "Safety Specialist": ["Risk Assessment", "OSHA Compliance", "Safety Audits", "Incident Investigation"],
    "Logistics Specialist": ["Supply Chain Management", "Warehouse Operations", "Inventory Control", "Transportation Planning"],
    "Game Developer": ["Unity3D", "Unreal Engine", "C#", "C++", "Game Physics", "AI for Games"],
    "Retail Expert": ["Point of Sale Systems", "Inventory Management", "Customer Analytics", "E-commerce Platforms"],
    "Satellite Data Analyst": ["Remote Sensing", "Geographic Information Systems (GIS)", "Python", "Matlab", "Image Processing"],
    "Aerospace Engineer": ["CAD", "Aerodynamics", "Avionics", "Propulsion Systems", "Simulation Tools"],
    "Drone Specialist": ["Flight Control Systems", "Drone Programming", "Sensor Integration", "Battery Management"],
    "Aerospace Technician": ["Mechanical Systems", "Diagnostics Tools", "Avionics Maintenance", "Blueprint Reading"],
    "Astronaut Trainer": ["Zero-Gravity Operations", "Safety Protocols", "Astronaut Suit Systems", "Mission Simulations"],
    "Education Consultant": ["Curriculum Design", "Instructional Design", "Learning Management Systems (LMS)", "Assessment Strategies"],
    "Education Specialist": ["Teaching Techniques", "Education Technology", "Content Development", "Training Modules"],
    "Science Educator": ["Experiment Design", "STEM Curriculum", "Lab Safety Protocols", "Engagement Strategies"]
};

module.exports = {
    ROLES,
    ROLE_SKILLS
}